name: Push Check

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        go: [ 1.18.x,1.19.x,1.20.x,1.21.x,1.22.x]
    runs-on: ubuntu-latest

    services:
      nacos:
        image: 'nacos/nacos-server:v2.4.0.1'
        ports:
          - '8848:8848'
          - '9848:9848'
        env:
          MODE: standalone

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Module cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: typos-action
        uses: crate-ci/typos@v1.2.1

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./...

      - name: Unit Test
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
        env:
          serverAddr: 127.0.0.1
          serverPort: 8848
          namespace: public

